# Generated by Django 4.2.4 on 2023-08-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_02'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_02',
        ),
    ]
