# Generated by Django 4.2.4 on 2023-09-03 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_product_02'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='texPrice',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postcode',
            new_name='postalCode',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
